---
- src: stafwag.libvirt
- src: stafwag.delegated_vm_install
- src: stafwag.qemu_img
- src: stafwag.cloud_localds
- src: stafwag.virt_install_import
- src: stafwag.virt_install_vm
- src: stafwag.etc_hosts
- src: xanmanning.k3s
