---
# Create the kvm_hosts group
# add_host doesn't seem to work with multiple hosts at the
# same time. Setting serial: 1 to the hosts 1 by 1.
- hosts: k3s_cluster
  gather_facts: false
  become: false
  serial: 1
  tasks:
    - name: Create kvm host group
      import_role: name=create_kvm_host_group
      delegate_to: localhost

# Run the install play on the required roles
# Install the required packages for on the kvm
# hypervisors
- hosts: kvm_hosts
  gather_facts: true
  become: true
  roles:
     - role: requirements

# Enable the default libvirt network
# If you want to use a diffirent bridge this
# needs to configured on the host
- hosts: kvm_hosts
  gather_facts: true
  become: true
  tasks:
    - name: enable default libvirt network
      community.libvirt.virt_net:
        autostart: true
        command: start
        name: default

# Create the virtual machines
- name: Setup the virtual machine
  hosts: k3s_cluster
  become: true
  gather_facts: false
  any_errors_fatal: true
  roles:
     - role: stafwag.delegated_vm_install
       vars:
         ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Install k3s
- name: Install k3s
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: xanmanning.k3s
